### ISSUE TITLE
[☁️ Consultoria] Implantação de Nuvem Azure para Power BI (Dezembro de 2023)

### ISSUE THREAD

**Issue by RedeDSBR** [Rede-DSBR/PNP#101]
## **Distribuição das Horas:**

- [x] **Sprint 01. Conhecimento da Infraestrutura Atual e Estratégias Iniciais:** 01 horas 📊
- [x] **Sprint 02. Configuração inicial do Ambiente Azure:** 02 horas ⚙️
- [x] **Sprint 03. Apresentação e compreensão de pipeline de Dados Orçamentários:** 02 horas 🚀
- [x] **Sprint 04. Proposição no ambiente Azure de pipeline para Dados Orçamentários:** 02 horas 🚀
- [x] **Sprint 05. Apresentação e compreensão do consumo de dados orçamentários na Plataforma Nilo Peçanha** 02 horas 🚀
---

# **Atividades Realizadas**

## Sprint 01: Conhecimento da Infraestrutura Atual e Estratégias Iniciais de Implantação

📅 **Data:** 16/12/2023  
🕒 **Horário:** 19:00 - 20:10  

### Resumo:

Familiarização com a infraestrutura atual, fontes e pipeline de dados. Organização de sessões para configuração e implementação de pipeline de dados orçamentários. Apresentação da Infraestrutura de dados existente, incluindo plataformas e ferramentas em uso, discussão sobre fontes de dados atuais e sua integração no processo de negócio. Estratégias Iniciais para Implementação, Identificação das áreas chave para otimização do pipeline de dados. Discussão de abordagens preliminares para implantação e processamento analítico de dados.

### Encaminhamentos:

- Agendamento de quatro sessões de trabalho (terças e quintas) até 31/12/2023. Foco nas sessões será a configuração inicial prática e implementação do pipeline de dados orçamentários.
- **Tarefa de Casa**: o treinamento on line sobre Fundamentos do Microsoft Azure pode ser realizado em três etapas. O acesso pode ser realizado diretamente no link [**Princípios básicos do Microsoft Azure**](https://learn.microsoft.com/pt-br/training/paths/microsoft-azure-fundamentals-describe-cloud-concepts/) 

### **Materiais de Referência**
- [SIGA Brasil - Portal do Orçamento](https://www12.senado.leg.br/orcamento/sigabrasil)
- [SIOP - Painel do Orçamento Federal](https://www1.siop.planejamento.gov.br/QvAJAXZfc/opendoc.htm?document=IAS%2FExecucao_Orcamentaria.qvw&host=QVS%40pqlk04&anonymous=true&sheet=SH06)
- [Painel Estatístico de Pessoal](http://painel.pep.planejamento.gov.br/QvAJAXZfc/opendoc.htm?document=painelpep.qvw&lang=en-US&host=Local&anonymous=true)
- [Tesouro Gerencial](https://tesourogerencial.tesouro.gov.br/tg/servlet/mstrWeb?pg=login&v=1702861370575)
- [Planilhas de Fontes/Bases de dados do Universidade 360](https://docs.google.com/spreadsheets/d/1z9pE5NmlJzL9YOo1e38Pn68w1YPGwdNSeQYD9p9zLKI/edit?usp=sharing)
***

## **Sprint 02**: Configuração do Ambiente Azure

📅 **Data:** 19/12/2023  
🕒 **Horário:** 20:30 - 22:30  
📹 [**Link para a gravação**](https://drive.google.com/file/d/19h3qwFzwRoi8SdNgJ3GJnvCHPl_TtJW1/view)

### Resumo:

Nesta sessão, focamos na configuração essencial do ambiente Azure para nosso projeto. A sessão começou com a criação de contas e grupos de usuários no Microsoft Entra, estabelecendo uma estrutura básica para acesso e gerenciamento de permissões. Exploramos também a criação de grupos de produtos e discutimos estratégias para integrar serviços gratuitos do Azure, visando maximizar a eficiência e reduzir custos. Foram tópicos discutidos 1. Configuração de Contas e Acesso no Azure, 2. Criação de Grupos de Usuários e Produtos, 3. Exploração de Serviços Gratuitos do Azure

### Encaminhamentos:

- **Tarefa de Casa**: Realizar o treinamento online sobre Fundamentos do Microsoft Azure em três etapas. O acesso pode ser realizado diretamente no link [**Princípios básicos do Microsoft Azure**](https://learn.microsoft.com/pt-br/training/paths/microsoft-azure-fundamentals-describe-cloud-concepts/)

### Materiais de Referência:
- [Serviços Gratuitos Azure](https://azure.microsoft.com/pt-br/free)
- [Calculadora de Preços Azure](https://azure.microsoft.com/pt-br/pricing/calculator)
- [Comparação de preço das principais nuvens](https://holori.com/cloud-calculator/)
- [Princípios básicos do Microsoft Azure](https://learn.microsoft.com/pt-br/training/paths/microsoft-azure-fundamentals-describe-cloud-concepts/)
- [Administrador Office](https://admin.microsoft.com)

🖼️ Imagens:

![Image](https://github.com/Rede-DSBR/PNP/assets/102130353/acb4175b-fcf6-4727-b2a9-b3d7c44e6478)

![Image](https://github.com/Rede-DSBR/PNP/assets/102130353/6396c1d9-c92d-47de-baed-63dd1616062c)

***
## **Sprint 03**: Integrações de Dados Orçamentários

📅 **Data:** 21/12/2023  
🕒 **Horário:** 20:30 - 22:05  
📹 [**Link para a gravação**](https://drive.google.com/file/d/1IyyVZHfnoca9SENysFfvC9pa8h1EIJsq/view)

### Resumo:

Apresentamos a estratégia completa de processamento de dados orçamentários, discutindo o processo de orçamentação brasileiro, as fases de programação e execução da despesa, a construção e subscrição de relatórios no tesouro gerencial, plataforma de fornecimento de dados. Discutimos o processo de captura de arquivos informações que são enviadas por email e o seu processamento no Pentaho, os arquivos de dimensão e fatos gerados e consumidos no Power BI, o cliente dos dados processados.

### Materiais de Referência:

- [Modelo ontológico da Classificação das Despesas do Orçamento Federal Brasileiro](https://web.archive.org/web/20200217035948/http://vocab.e.gov.br/2013/09/loa)
- [Manual Técnico do Orçamento - MTO 2023](https://www1.siop.planejamento.gov.br/mto/doku.php/mto2023)

🖼️ Imagens:

![image](https://github.com/Rede-DSBR/PNP/assets/102130353/4b5d81b2-e742-440b-84e8-29d5f49116ea)

![image](https://github.com/Rede-DSBR/PNP/assets/102130353/f6701278-aff1-4d60-a998-8634ca90c755)

![image](https://github.com/Rede-DSBR/PNP/assets/102130353/905240f3-a6fb-4c76-963f-043da533c3da)

***
## **Sprint 04**: Proposição preliminar de infraestrutura de dados na Nuvem Azure

📅 **Data:** 28/12/2023  
🕒 **Horário:** 20:30 - 22:10  
📹 [**Link para a gravação**](https://drive.google.com/file/d/1-rnJ9AWluRqW9tX_LIPkHQ6d2S8Gr-L0/view)

### Resumo:
Foi realizada uma análise da infraestrutura de dados orçamentárias com diagrama e apresentada propostas de abordagem dos processos a partir dos artefatos em nuvem disponíveis na infraestrutura Azure. Discutimos o processo de dados, os clientes da infraestrutura e produtos analíticos que devem ser entregues. Foram tópicos abordados na seção a 1. Análise preliminar de solução, 2. Produtos de dados, 3. Artefatos em nuvem Azure.

### Encaminhamento
- Definir quais são os produtos de dados que vamos entregar;
- Definir os usuários e a estratégia de acesso para cada um deles;
- [Treinamento: Introdução ao Data Factory](https://learn.microsoft.com/pt-br/training/modules/intro-to-azure-data-factory/)

### Materiais de Referência:

- [Apresentação sobre a Análise Geral e Proposta Preliminar de Solução](https://drive.google.com/open?id=19I_MKwhl6ucBWbORygNMsAkBa6L4YD4W&usp=drive_fs)
- [Manual Técnico Orçamentário 2023](https://www1.siop.planejamento.gov.br/mto/doku.php/mto2023)
- [Convenção Azure para nomenclatura de recurso computacional](https://learn.microsoft.com/pt-br/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
- [Preços do Functions do Azure, funções de código sem servidor controladas por eventos](https://azure.microsoft.com/pt-br/pricing/details/functions/)
- [Preços do Aplicativos Lógicos](https://azure.microsoft.com/pt-br/pricing/details/logic-apps/)
- [Preços do Key Vault](https://azure.microsoft.com/pt-br/pricing/details/key-vault/)
- [Introdução ao Data Factory](https://learn.microsoft.com/pt-br/training/modules/intro-to-azure-data-factory/)

🖼️ Registro de imagens:

![image](https://github.com/Rede-DSBR/PNP/assets/102130353/98bb9735-6d31-4ab5-a96d-61b9d327c0d6)

![image](https://github.com/Rede-DSBR/PNP/assets/102130353/fc6a876a-edf6-4099-b712-942667003d75)

![image](https://github.com/Rede-DSBR/PNP/assets/102130353/c5213e57-77a6-4266-9788-099cb4b8710a)

***
## **Sprint 05**: Plataforma Nilo Peçanha

📅 **Data:** 29/12/2023  
🕒 **Horário:** 20:30 - 22:10  
📹 [**Link para a gravação**](https://drive.google.com/file/d/1qqdFaJXKN1T_oJ0xPWsHPY_SFDicU9SW/view)

### Resumo:
A arquitetura e estrutura de conhecimento da Plataforma Nilo Peçanha foi apresentada com especial atenção para o processo de ETL e de construção do modelo semântico. Discutimos a infraestrutura de dados de ponta a ponta e realizamos algumas reflexões sobre a estrutura de distribuição de dados construída no contexto da estruturação de artefatos no ambiente Azure. Foram apontadas necessidades de melhorias de na visualização e até mesmo a manutenção de visuais que necessitam de correção. Entre outros pontos, foram os principais tópicos discutidos 1. Carregamento, transformação , 2. Distribuição de dados, 3. Artefatos de visualização da PNP

### Encaminhamento
- Realizar teste de integração do modelo semântico da PNP no ambiente Azure.

### Materiais de Referência:

- [Plataforma Nilo Peçanha](https://www.gov.br/mec/pt-br/pnp)

### 🖼️ Registro de imagens

![image](https://github.com/Rede-DSBR/PNP/assets/102130353/5e4d997f-652e-484d-8b70-f76210b0385e)

![image](https://github.com/Rede-DSBR/PNP/assets/102130353/48351aae-8c34-42e0-a4e2-b172b2658637)=

![image](https://github.com/Rede-DSBR/PNP/assets/102130353/024fac7d-a895-458f-bf2a-1bc1bd3a3e69)

![image](https://github.com/Rede-DSBR/PNP/assets/102130353/c73276fb-ef2e-403f-87f5-69b323d0653b)

**Comment by ProfSadala** [comment]
https://learn.microsoft.com/api/achievements/share/pt-pt/MarcosViniciusSadalaBarreto-0972/24C235UV?sharingId=D4F4E87F85591397
https://learn.microsoft.com/api/achievements/share/pt-pt/MarcosViniciusSadalaBarreto-0972/WABWTETN?sharingId=D4F4E87F85591397
Curso bom, bem explicado. Aprovado!!!!

**Comment by rogerioluizsi** [comment]
@RedeDSBR , todos os links para a gravações das reuniões, exceto do primeiro encontro (19/12), apontam  para a gravação do dia 21/12.  A gravação do dia 19/12 tb não tem permissão para acesso.

**Comment by RedeDSBR** [comment]
Vou verificar @rogerioluizsi
