### ISSUE TITLE
Identificar e diagnosticar as fontes de dados necessárias ao fluxo referente à dinâmica do mundo do trabalho.

### ISSUE THREAD

**Issue by bmarbueno** [Rede-DSBR/PNP#130]
#### Requisitos de acesso:
Os microdados do Novo CAGED estão disponíveis em formato texto (.txt) e com delimitador ";" (codificado em UTF-8), por meio de protocolo FTP. A conexão de dados disponibilizados por meio de protocolo FTP pode ser realizada, dentre outras formas, com a utilização do [Power Automate](https://www.linkedin.com/pulse/how-connect-microsoft-power-bi-data-sftp-ftp-marcos-fattibello/) ou do [Pentaho](https://www.linkedin.com/pulse/enviando-e-puxando-arquivos-atrav%C3%A9s-de-ftp-usando-gutierres-damaceno/?originalSubdomain=pt).
#### Qualidade dos Dados:
Conforme Nota Técnica MTPS 088/12, atualizado em 29/03/2016:

> O Ministério do Trabalho e Previdência Social liberou à comunidade usuária o acesso aos microdados da Relação Anual de Informações Sociais – RAIS e Cadastro Geral de Empregados e Desempregados –CAGED.
Ressalta-se, no entanto, que nestes microdados estão disponíveis variáveis, como por exemplo, Indicador de Pessoa com Deficiência, Tipo de Deficiência, Atividade Econômica (Subclasse), Ocupação e Raça/Cor que devem ser utilizadas com certa cautela, pois, algumas são relativamente novas e outras, dado o nível de desagregação, podem apresentar algumas inconsistências. Contudo, em termos gerais, sua utilização em nível mais agregado não está comprometida.
Mais informações sobre utilização e cuidados com dados dos Registros  Administrativos do Programa de Disseminação de Estatísticas do Trabalho - PDET – podem ser obtidas nas Notas Técnicas e Comunicados disponibilizados no endereço:
http://acesso.mte.gov.br/portal-pdet/ajuda/notas-tecnicas-e-comunicados/notastecnicas-e-comunicados.htm
Para esclarecimentos adicionais, recomenda-se fazer contato com a CGET no endereço eletrônico cget.sppe@mte.gov.br
O Ministério do Trabalho e previdência Social, por meio da Coordenação Geral de Estatísticas do Trabalho (CGET), mantém uma comunidade que trata de questões relacionadas ao Programa de Disseminação de Estatísticas do Trabalho (PDET) e assuntos relacionados ao Mercado de Trabalho em nível nacional.
Para ingressar na comunidade "BasesMTE" envie uma mensagem eletrônica para basesmte-subscribe@yahoogrupos.com.br.

Conforme Comunicado MTPS 192/12:

> Em continuidade a reestruturação do Programa de Disseminação de Estatísticas do Trabalho, conforme informado no Comunicado 189/2011, de 08/11/2011, estamos disponibilizando no endereço ftp://ftp.mtps.gov.br/pdet/microdados/, aos usuários do PDET, microdados, não identificados, do CAGED Estatístico, desde janeiro de 2009, e da RAIS Estabelecimento e Trabalhador desde o ano-base de 1998, em texto (.txt) para utilização em aplicativos estatísticos como, por exemplo, SPSS 
ou SAS ou R.
Para esclarecimentos adicionais, recomenda-se fazer contato com a CGET no endereço eletrônico cget.sppe@mte.gov.br.
O Ministério do Trabalho e Previdência Social, por meio da Coordenação Geral de Estatísticas do Trabalho (CGET), mantém uma comunidade que trata de questões relacionadas ao Programa de Disseminação de Estatísticas do Trabalho (PDET) e assuntos relacionados ao Mercado de Trabalho em nível nacional. Para ingressar na comunidade "BasesMTE" envie uma mensagem eletrônica para: basesmte-subscribe@yahoogrupos.com.br.

#### Documentação:
Desde janeiro de 2020, o uso do Sistema do Cadastro Geral de Empregados e Desempregados (Caged) foi substituído pelo Sistema de Escrituração Digital das Obrigações Fiscais, Previdenciárias e Trabalhistas (eSocial) para parte das empresas, conforme estabelecido pela Portaria SEPRT nº 1.127, de 14/10/2019. Permanece a obrigatoriedade de envio das informações por meio do Caged apenas para órgãos públicos e organizações internacionais que contratam celetistas.
Embora a maior parte das empresas esteja obrigada a declarar o eSocial, muitas deixaram de prestar informações de desligamentos a este sistema. Para viabilizar a divulgação das estatísticas do emprego formal durante esse período de transição, foi feita a imputação de dados de outras fontes.
O Novo Caged é a geração das estatísticas do emprego formal por meio de informações captadas dos sistemas eSocial, Caged e Empregador Web.
A metodologia de imputação adotada para o ajuste das informações prestadas ao eSocial e ao Caged visa assegurar a qualidade e a integridade das estatísticas do emprego formal durante a transição dessas fontes de captação de dados. A SEPRT apura tecnicamente o recebimento dessas informações nos registros administrativos e atua de forma a divulgar as 
estatísticas do emprego formal com segurança metodológica e transparência.
A partir da divulgação da competência de outubro de 2021 a metodologia de consolidação das informações dos três sistemas foi atualizada para captar um maior número de movimentações aperfeiçoando a divulgação das estatísticas do mercado de trabalho formal.
Para detalhamento da metodologia do Novo Caged, acesse a Nota Técnica aqui: http://pdet.mte.gov.br/o-que-e-novo-caged
O layout dos microdados do Novo Caged está disponível no arquivo:
[Layout Não-identificado Novo Caged Movimentação.xlsx](https://github.com/Rede-DSBR/PNP/files/14065031/Layout.Nao-identificado.Novo.Caged.Movimentacao.xlsx)

#### Requisitos de acesso:
A base está disponível via [API](https://servicodados.ibge.gov.br/api/v1/localidades/municipios) que retorna o conjunto de municípios do Brasil.
#### Documentação:
A versão da API 1.0.0 atualmente disponível, refere-se às divisões político-administrativas do Brasil bem como meso e microrregiões, institucionalizadas pela aprovação da presidência do IBGE da resolução PR nº 51/1989 e pela publicação Divisão regional do Brasil em mesorregiões e microrregiões geográficas.
obs 1: os identificadores providos pela API são oficialmente designados pelo IBGE.
obs 2: as regiões geográficas imediatas e intermediárias decorrem da revisão das microrregiões e mesorregiões diante do expressivo aumento das diferenças inter-regionais, como resultado das mudanças econômicas, demográficas, políticas e ambientais ocorridas ao longo das últimas décadas. Assim, as regiões geográficas imediatas e intermediárias serão periodicamente revisadas, visando oferecer elementos para a compreensão da realidade brasileira. Adicionalmente, passam a substituir as mesorregiões e microrregiões geográficas de forma progressiva até 21/12/2023. Para maiores informações, incluindo metodologia e nomenclatura, acesse [Divisão regional do Brasil em regiões geográficas imediatas e regiões geográficas intermediárias](https://www.ibge.gov.br/geociencias/cartas-e-mapas/redes-geograficas/15778-divisoes-regionais-do-brasil.html)

![image](https://github.com/Rede-DSBR/PNP/assets/57711724/daa55061-745e-45ec-b088-0f787576e522)

#### Script de teste da migração de dados:
Script de consulta em PowerQueryM:

```
let
    Fonte = Json.Document(Web.Contents("https://servicodados.ibge.gov.br/api/v1/localidades/municipios")),
    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Column1 Expandido" = Table.ExpandRecordColumn(#"Convertido para Tabela", "Column1", {"id", "nome", "microrregiao", "regiao-imediata"}, {"id", "nome", "microrregiao", "regiao-imediata"}),
    #"microrregiao Expandido" = Table.ExpandRecordColumn(#"Column1 Expandido", "microrregiao", {"id", "nome", "mesorregiao"}, {"microrregiao.id", "microrregiao.nome", "microrregiao.mesorregiao"}),
    #"microrregiao.mesorregiao Expandido" = Table.ExpandRecordColumn(#"microrregiao Expandido", "microrregiao.mesorregiao", {"id", "nome", "UF"}, {"microrregiao.mesorregiao.id", "microrregiao.mesorregiao.nome", "microrregiao.mesorregiao.UF"}),
    #"microrregiao.mesorregiao.UF Expandido" = Table.ExpandRecordColumn(#"microrregiao.mesorregiao Expandido", "microrregiao.mesorregiao.UF", {"id", "sigla", "nome", "regiao"}, {"microrregiao.mesorregiao.UF.id", "microrregiao.mesorregiao.UF.sigla", "microrregiao.mesorregiao.UF.nome", "microrregiao.mesorregiao.UF.regiao"}),
    #"microrregiao.mesorregiao.UF.regiao Expandido" = Table.ExpandRecordColumn(#"microrregiao.mesorregiao.UF Expandido", "microrregiao.mesorregiao.UF.regiao", {"id", "sigla", "nome"}, {"microrregiao.mesorregiao.UF.regiao.id", "microrregiao.mesorregiao.UF.regiao.sigla", "microrregiao.mesorregiao.UF.regiao.nome"}),
    #"regiao-imediata Expandido" = Table.ExpandRecordColumn(#"microrregiao.mesorregiao.UF.regiao Expandido", "regiao-imediata", {"id", "nome", "regiao-intermediaria"}, {"regiao-imediata.id", "regiao-imediata.nome", "regiao-imediata.regiao-intermediaria"}),
    #"regiao-imediata.regiao-intermediaria Expandido" = Table.ExpandRecordColumn(#"regiao-imediata Expandido", "regiao-imediata.regiao-intermediaria", {"id", "nome", "UF"}, {"regiao-imediata.regiao-intermediaria.id", "regiao-imediata.regiao-intermediaria.nome", "regiao-imediata.regiao-intermediaria.UF"}),
    #"regiao-imediata.regiao-intermediaria.UF Expandido" = Table.ExpandRecordColumn(#"regiao-imediata.regiao-intermediaria Expandido", "regiao-imediata.regiao-intermediaria.UF", {"id", "sigla", "nome", "regiao"}, {"regiao-imediata.regiao-intermediaria.UF.id", "regiao-imediata.regiao-intermediaria.UF.sigla", "regiao-imediata.regiao-intermediaria.UF.nome", "regiao-imediata.regiao-intermediaria.UF.regiao"}),
    #"regiao-imediata.regiao-intermediaria.UF.regiao Expandido" = Table.ExpandRecordColumn(#"regiao-imediata.regiao-intermediaria.UF Expandido", "regiao-imediata.regiao-intermediaria.UF.regiao", {"id", "sigla", "nome"}, {"regiao-imediata.regiao-intermediaria.UF.regiao.id", "regiao-imediata.regiao-intermediaria.UF.regiao.sigla", "regiao-imediata.regiao-intermediaria.UF.regiao.nome"}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"regiao-imediata.regiao-intermediaria.UF.regiao Expandido",{{"id", Int64.Type}, {"nome", type text}, {"microrregiao.id", Int64.Type}, {"microrregiao.nome", type text}, {"microrregiao.mesorregiao.id", Int64.Type}, {"microrregiao.mesorregiao.nome", type text}, {"microrregiao.mesorregiao.UF.id", Int64.Type}, {"microrregiao.mesorregiao.UF.sigla", type text}, {"microrregiao.mesorregiao.UF.nome", type text}, {"microrregiao.mesorregiao.UF.regiao.id", Int64.Type}, {"microrregiao.mesorregiao.UF.regiao.sigla", type text}, {"microrregiao.mesorregiao.UF.regiao.nome", type text}, {"regiao-imediata.id", Int64.Type}, {"regiao-imediata.nome", type text}, {"regiao-imediata.regiao-intermediaria.id", Int64.Type}, {"regiao-imediata.regiao-intermediaria.nome", type text}, {"regiao-imediata.regiao-intermediaria.UF.id", Int64.Type}, {"regiao-imediata.regiao-intermediaria.UF.sigla", type text}, {"regiao-imediata.regiao-intermediaria.UF.nome", type text}, {"regiao-imediata.regiao-intermediaria.UF.regiao.id", Int64.Type}, {"regiao-imediata.regiao-intermediaria.UF.regiao.sigla", type text}, {"regiao-imediata.regiao-intermediaria.UF.regiao.nome", type text}})
in
    #"Tipo Alterado"
```

#### Requisitos de acesso:
A estrutura da Classificação Brasileira de ocupações (CBO) está disponível em arquivo csv compactado (zip) no [site do ministério do trabalho](http://www.mtecbo.gov.br/cbosite/pages/downloads.jsf). Além disso, no [layout do Novo Caged](https://github.com/Rede-DSBR/PNP/files/14065031/Layout.Nao-identificado.Novo.Caged.Movimentacao.xlsx) há uma visão das descrições da CBO.
#### [Documentação](http://www.mtecbo.gov.br/cbosite/pages/informacoesGerais.jsf):
A Classificação Brasileira de Ocupações - CBO é o documento normalizador do reconhecimento, para fins classificatórios, da nomeação e da codificação dos títulos e conteúdos das ocupações do mercado de trabalho brasileiro. É ao mesmo tempo uma classificação enumerativa e uma classificação descritiva.
- Classificação enumerativa: codifica empregos e outras situações de trabalho para fins estatísticos de registros administrativos, censos populacionais e outras pesquisas domiciliares. Inclui códigos e títulos ocupacionais e a descrição sumária. Ela também é conhecida pelos nomes de nomenclatura ocupacional e estrutura ocupacional.
- Classificação descritiva: inventaria detalhadamente as atividades realizadas no trabalho, os requisitos de formação e experiência profissionais e as condições de trabalho.

A função enumerativa da CBO é utilizada em registros administrativos como a Relação Anual de Informações Sociais - Rais, Cadastro Geral de Empregados e Desempregados - Caged, Seguro Desemprego, Declaração do Imposto de Renda de Pessoa Física - Dirpf, dentre outros. Em pesquisas domiciliares é utilizada para codificar a ocupação como, por exemplo, no Censo Demográfico, na Pesquisa Nacional por Amostra de Domicílios - Pnad e outras pesquisas de institutos de estatísticas como o IBGE e congêneres nas esferas dos estados e dos municípios.
A função descritiva é utilizada nos serviços de recolocação de trabalhadores como o realizado no Sistema Nacional de Empregos - Sine, na elaboração de currículos e na avaliação de formação profissional, nas atividades educativas das empresas e dos sindicatos, nas escolas, nos serviços de imigração, enfim, em atividades em que informações do conteúdo do trabalho sejam requeridas.
A documentação completa está disponível em http://www.mtecbo.gov.br/cbosite/pages/informacoesGerais.jsf.

#### Requisitos de acesso:
Para obter acesso aos microdados disponibilizados em formato xlsx, é preciso preencher um cadastro e realizar o download no [site da secretaria de trabalho do Ministério do Trabalho](https://qbqconsulta.fipe.org.br/loginDados)
#### Documentação:
Em 2019, foi iniciado o projeto “Estudo, Elaboração e Implantação do QBQ - Quadro Brasileiro de Qualificações”, com a fase de planejamento e de definição dos critérios e dos descritores para classificar o nível de qualificação de uma ocupação. O estudo, implementado pela Coordenação da Classificação Brasileira de Ocupações (CCBO), define como principais objetivos do QBQ:
Definir o nível de qualificação de cada ocupação constante da Classificação Brasileira de Ocupações (CBO);
Subsidiar a elaboração de programas de qualificação profissional, com base na definição de perfis ocupacionais, conhecimentos, habilidades e atitudes em cada ocupação;
Subsidiar o estabelecimento de prioridades para atualização da CBO;
Viabilizar a articulação dos sistemas de formação profissional do Brasil com os de outros países.
Desse modo, o QBQ pretende contribuir para o acompanhamento das transformações do mundo do trabalho, subsidiando a adequação de programas de aperfeiçoamento e atualização profissional dos trabalhadores à nova realidade e a criação de programas de formação inicial do jovem brasileiro apropriados às novas oportunidades de empregos.
Em 2020, iniciou-se a divulgação das ocupações da CBO analisadas e inseridas no padrão do QBQ. Tratava-se de uma versão de avaliação para colher, de potenciais usuários, o maior número possível de sugestões de melhorias.
Em setembro de 2022, um total de 1.800 ocupações estão divulgadas e melhorias - como o acesso ao conjunto das informações divulgadas em tabela Excel - estão implantadas no processo de divulgação em atendimento às solicitações feitas por usuários.
Com relação a cada ocupação divulgada, é possível ter-se acesso à classificação do nível de qualificação, ao perfil ocupacional (em versões síntese e detalhada), bem como à relação de conhecimentos, habilidades e atitudes.
Na primeira etapa de implantação do QBQ, foi dada prioridade às ocupações dos Grandes Grupos CBO 3 (Técnicos de nível médio) e 4 a 9 (Trabalhadores da agropecuária, indústria, comércio e serviços). Na segunda etapa, deu-se início à inserção das ocupações do Grande Grupo CBO 2 (Profissionais das ciências e das artes) no QBQ.
As propostas encaminhadas pelos diferentes setores da sociedade continuam sendo fundamentais para melhoria da divulgação e para o contínuo processo de atualização e aperfeiçoamento das informações divulgadas. Contamos com as contribuições de todos. 
##### O Quadro Brasileiro de Qualificações (QBQ)
Inspirado no Quadro Europeu e seus congêneres, criou-se o Quadro Brasileiro de Qualificações (QBQ).
O principal diferencial do Quadro Brasileiro de Qualificações, em relação aos demais (QEQ e QNQ), é o fato de seu ponto de partida ser a descrição das ocupações do mercado de trabalho e não os sistemas de educação e formação profissional.
O Quadro Brasileiro de Qualificações pode ser definido como um conjunto de informações - perfis ocupacionais e indicadores associados aos conhecimentos, às habilidades e às atitudes - que, de forma articulada, permitem delinear o preparo necessário ao desempenho do trabalhador em cada ocupação oficialmente reconhecida no mercado de trabalho brasileiro.
Nesse sentido, no QBQ, Qualificação é o resultado esperado de aprendizagem – em relação aos conhecimentos, habilidades e atitudes – para o desempenho de atividades ou funções típicas de uma ocupação, no mercado de trabalho.
A Qualificação passa a corresponder a um programa de educação profissional quando especialistas de instituições de ensino profissional definem a duração, a organização curricular e as estratégias de ensino para alcance de tal “resultado esperado de aprendizagem”.
O Quadro Brasileiro de Qualificações tem, como campo de abrangência, as cerca de 2.700 ocupações constantes da Classificação Brasileira de Ocupações (CBO).
A CBO é o documento normalizador do reconhecimento, da nomeação e da codificação dos títulos e dos conteúdos das ocupações do mercado de trabalho brasileiro. Nela, ocupação é definida como “a agregação de empregos ou situações de trabalho similares quanto às atividades realizadas”.(2)
No âmbito de cada ocupação, é possível identificar as atividades realizadas pelo trabalhador. Essas atividades, formatadas em tabela, são a base para a primeira etapa da classificação de uma ocupação no Quadro Brasileiro de Qualificações. A definição do Perfil Ocupacional usa, como uma de suas fontes de informação, a tabela que consta na CBO. Além dela, são pesquisadas informações sobre as mudanças tecnológicas ou na organização de trabalho, ocorridas no âmbito da ocupação.
Normalmente, para elaborar o perfil ocupacional, trabalha-se com perguntas chaves: o que faz? e como faz? e, eventualmente, para quê?
A definição do perfil ocupacional é o ponto de referência para análise dos conhecimentos, habilidades e atitudes essenciais para o desempenho de uma ocupação.
![image](https://github.com/Rede-DSBR/PNP/assets/57711724/aed10f06-9afb-4b9c-9a52-1cfdce98939f)
A partir da análise da complexidade e/ou profundidade de conhecimentos e habilidades, e da consideração da autonomia e da responsabilidade que um indivíduo deverá ser capaz de demonstrar, a ocupação é classificada em determinado nível de qualificação.
O QBQ estrutura-se em oito níveis de qualificação, apresentados a seguir.
![image](https://github.com/Rede-DSBR/PNP/assets/57711724/a012b19d-8983-4463-a091-32c3eb093d21)
Nos níveis de qualificação, os aumentos contínuos de complexidade, profundidade e diversidade em conhecimentos e habilidades, além de autonomia e responsabilidade em atitude, podem ser visualizados na figura a seguir.
![image](https://github.com/Rede-DSBR/PNP/assets/57711724/e5533aa7-43a7-47e4-9faa-bdc13a9ce16b)
Foram enquadradas em NC (Não Classificada) as ocupações com processos especiais - tais como nomeação por autoridades e processos eleitorais - de inserção no mercado de trabalho.
Finalmente, cabe ressaltar que as ocupações foram separadas, para realização dos trabalhos, em dois grupos:

- Grupo I - ocupações de níveis 1 a 5 – demandam programas de educação profissional e tecnológica.
- Grupo II - ocupações de níveis 6 a 8 – demandam nível de educação superior de Graduação (exceto formação de tecnólogos) e Pós-graduação, compreendendo programas de mestrado e doutorado, além de cursos de especialização e aperfeiçoamento.

Os detalhes sobre terminologia e conceitos estão disponíveis no [site da secretaria de trabalho do Ministério do Trabalho](https://qbqconsulta.fipe.org.br/Conceitos).

#### Requisitos de acesso:
O catálogo está disponível em formato [pdf ](http://cnct.mec.gov.br/cnct-api/catalogopdf) ou nas páginas de cursos do site eletrônico do catálogo.
#### Integridade dos Dados:
O catálogo é atualizado de tempos em tempos e encontra-se, atualmente, em sua 4ª Edição, com isso, há o risco de violações de integridade referencial dos dados.
#### Documentação:
O Catálogo Nacional de Cursos Técnicos (CNCT), aprovado pelo Conselho Nacional de Educação (CNE), por meio da [Resolução CNE/CEB nº 2 , de 15 de dezembro de 2020](https://www.in.gov.br/en/web/dou/-/resolucao-n-2-de-15-de-dezembro-de-2020-294347656), disciplina a oferta de cursos de educação profissional técnica de nível médio para orientar e informar as instituições de ensino, os estudantes, as empresas e a sociedade em geral. Seu conteúdo é atualizado periodicamente pelo Ministério da Educação para contemplar novas demandas socioeducacionais.
Para as instituições de ensino, o Catálogo é um referencial que subsidia o planejamento dos cursos e suas correspondentes qualificações profissionais e especializações técnicas de nível médio.
Para os estudantes, serve de base para a escolha dos seus cursos, apresentando-lhes os diferentes perfis profissionais e as possibilidades de atuação, entre outras informações.
E, para o setor produtivo, auxilia na definição da contratação de profissionais com os perfis mais adequados às suas necessidades.

### [Catálogo Nacional de Cursos Superiores de Tecnologia](http://portal.mec.gov.br/catalogos-nacionais-de-cursos-superiores-de-tecnologia)
O catálogo está disponível em formato [pdf](http://portal.mec.gov.br/docman/junho-2016-pdf/44501-cncst-2016-3edc-pdf/file).
#### Integridade dos Dados:
O catálogo é atualizado de tempos em tempos e sua última edição publicada (3ª Edição), publicada em 2016, está em processo de revisão. Com isso, há o risco de violações de integridade referencial dos dados.
#### Documentação:
O Catálogo Nacional de Cursos Superiores de Tecnologia (CNCST) é um referencial normativo específico para subsidiar o planejamento dos cursos de educação profissional tecnológica de nível superior, também chamados de Cursos de Tecnólogos ou Cursos Superiores de Tecnologia.
O Catálogo apresenta os nomes dos cursos e os respectivos perfis profissionais de conclusão. Seu objetivo é servir de referencial capaz de balizar os processos de regulação e supervisão de cursos, bem como de avaliação.
Dessa forma, o catálogo é instrumento orientador para alunos, instituições de educação superior, sistemas de ensino e público em geral. Contribuem ainda para conferir maior visibilidade e o reconhecimento público e social dessas graduações.
A 3ª edição do CNCST traz em sua estrutura 134 denominações de Cursos Superiores de Tecnologia, agrupados em 13 eixos tecnológicos, com a seguinte descrição por curso:

- perfil profissional de conclusão;
- infraestrutura mínima requerida;
- carga-horária mínima; campo de atuação;
- ocupações CBO associadas;
- possibilidades de prosseguimento de estudos na Pós-Graduação lato sensu e stricto sensu.

Além disso, consta na 3º edição do CNCST, como anexo, a Tabela de Convergência, contendo a relação de correspondência entre as denominações de cursos técnicos que não estão mais em uso e aquelas presentes no catálogo.

**Comment by RedeDSBR** [comment]
Excelente. Você fez um diagnóstico completo das bases que irão compor o modelo de dados. Vi que algumas tarefas já estão colocadas, como o acesso ao Quadro Brasileiro de Qualificações, onde é preciso preencher um cadastro para realizar o download no site da secretaria de trabalho do Ministério do Trabalho. Se achar oportuno pode criar uma caixinha de Check dessa tarefa para  apoiar o monitoramento; Parabéns pela entrega.
