### ISSUE TITLE
[🖼️ Conteúdo] Participação do Garcia na Sprint PNP de implantação de Infraestrutura Azure

### ISSUE THREAD

**Issue by RedeDSBR** [Rede-DSBR/PNP#132]
# 📝🖼️ Tarefa de Criação de Conteúdo

## 📖 Descrição
Fernando Garcia é um das maiores referências em Power BI do Brasil. Criador do canal [Planilheiros](https://www.youtube.com/@Planilheiros), Top Voice em Business Intelligence no LinkedIn,, Garcia, como é nacionalmente conhecido, é MVP da Microsoft e ocupa o cargo de Gerente Geral de Informações Estratégicas e Monitoramento do Sistema de Integridade da Petrobrás. Liderança Nacional, o nosso convidado especial atua na estruturação e modelagem de dados que fomentam a produção de informações, indicadores, inteligência em dados, estudos estratégicos de integridade baseados em modelos estatísticos, IA e em soluções detectivas de perícia e recuperação de ativos contingentes.

## 📌 Atividades

- [ ] Vídeo com máximo de 30s legendado com cortes e publicação de reels e story, no que couber, no Instagram, com convite para  [Instagram Planilheiros](https://www.instagram.com/planilheiros/), [Instagram Garcia](https://www.instagram.com/dicadogarcia/) e [Instagram Poty Lucena](https://www.instagram.com/potylucena/) como colaborador (verificar quantidade máxima permitida).
- [ ] Postagem para Publicação no [linkedin potylucena](https://www.linkedin.com/in/potylucena/);
- [ ] Material compartilhado e disponibilizado com a equipe DSBR para edição;
- [ ] Avaliar impacto da postagem e indicadores de curtidas, comentários e visualizações;

## 🎯 Objetivo do Conteúdo
Demonstrar autoridade, impacto da pesquisa, trazer seguidores por efeito colaborador.

## 🗓️ Data de Publicação Prevista
26/01/2024

## 🛠️ Referências
[Linkedin Garcia](https://www.linkedin.com/in/garciamartins/) 
[Linkedin Poty Lucena](https://www.linkedin.com/in/potylucena/)
[Instagram Garcia](https://www.instagram.com/dicadogarcia/)
[Instagram Poty Lucena](https://www.instagram.com/potylucena/)
[Instagram Planilheiros](https://www.instagram.com/planilheiros/)
[YouTube](https://www.youtube.com/@Planilheiros)

## 🏁 Data de Conclusão Prevista
26/01/2024

**Comment by dudabastos1973** [comment]
texto da postagem:
Ontem giramos nosso telescópio e apontamos para mais uma galáxia: mergulhamos no universo Power BI durante nosso sprint e a energia estava nas alturas! outra presença ilustre abrilhantou nosso evento: Fernando Garcia, o mestre do canal Planilheiros, uma verdadeira lenda do Power BI no Brasil. Como MVP da Microsoft e Gerente Geral de Informações Estratégicas na Petrobrás, Garcia trouxe não apenas conhecimento técnico, mas uma visão única sobre a importância dos dados na tomada de decisões estratégicas de uma organização. Nós, que somos fãs assumidos, recebemos dicas preciosas do ninja Garcia e, ontem, a inspiração foi além! Foi um dia épico com uma personalidade que inspirou a trajetória de todos nós! #DSBRSprint #PowerBI #Planilheiros #FernandoGarcia #DicadoGarcia #InspiraçãoBI #planilheiros #rededsbr #ufob #azure #microsoftazure

**Comment by dudabastos1973** [comment]
@Tamiresbarretoo eu vou postar no insta assim que Poty fizer a aprovação final, daí você insere os emojis e compartilha/controla nas demais redes, ok?

**Comment by dudabastos1973** [comment]
titulo, ainda em aprovação @RedeDSBR
Sprint Estelar: Fábio Garcia do Planilheiros Iluminando nosso time
com experiências inspiradoras.

fiquem à vontade para sugerir, mexer, criticar etc

**Comment by dudabastos1973** [comment]
![CARD 1080X1080 SPRINT GRACIA](https://github.com/Rede-DSBR/PNP/assets/144291118/bb346406-a6a8-4e07-9d55-45eedea2a3f5)

**Comment by RedeDSBR** [comment]
Post aprovado! Jogue duro @dudabastos1973

**Comment by dudabastos1973** [comment]
![Uploading CARD 1080X1080 SPRINT GRACIA.jpg…]()

**Comment by dudabastos1973** [comment]
![IMG-20240126-WA0079.jpg](https://github.com/Rede-DSBR/PNP/assets/144291118/177510be-5009-4ce5-9647-03095d4d9909)
