### ISSUE TITLE
[🚀Desenvolvimento] Migração de Infraestrutura de Dados do SIOP para a nuvem Azure

### ISSUE THREAD

**Issue by RedeDSBR** [Rede-DSBR/PNP#160]
# 🌟 Descrição
Os dados do Siop são transacionados no Pentaho e deverão ser migrados para a infraestrutura Azure, segundo a arquitetura desenvolvida pelo nosso consulto Fabio Santos

# 👤 Pesquisador líder da tarefa

**Rogério Luiz Cardoso**
_Pesquisador Cientista de Dados_
@rogerioluizsi 

# 🎯 Problema Crítico
A alimentação do dados do orçamento possui uma atualização diária e a estrutura de dados do Siop deve ser aprimorada para que seja distribuída em nuvem Azure.

## 💡 Como Pretende Resolver o Problema
[Altere conforme necessidade]

- [x] Atividade 01 -  Ingestão dos dados do SIOP no AZURE data lake por meio de consultas SPARQL
- [x] #169
- [x] #170
- [x] #171

## 🛠️ Recursos Necessários

 - Acesso ao AZURE com privilégios
 - Reuniões com o stakeholders para entender como os dados serão consumidos
- Azure Data Factory ( ou Datafabric.)

## 📦 Entregáveis

- [x] #191

## 📚 Materiais de Referência

1. [Código e dados da infraestrutura atual de coleta e transformação de dados do Siop](https://drive.google.com/open?id=15cx2mwQSkhF03L7-YNYKsMC883ikTVpN&usp=drive_fs)
2. [Vídeo da estruturação de Pipeline de dados do Portal do Orçamento do Siop](https://drive.google.com/file/d/1N7iVgMJ0Q_FEOBcETLrc86vC0jXtCCU7/view)

## 🗂️ Pasta de Arquivos
📁 [Dados Orçamentários](https://drive.google.com/open?id=15cx2mwQSkhF03L7-YNYKsMC883ikTVpN&usp=drive_fs)

**Comment by rogerioluizsi** [comment]
Arquivos disponibilzados por meio de container publico conforme arquivos atuais.

Foi discutido a possibilidade  de rastrear as mudanças da base ao longo do tempo à partir do conceito de slowing time dimension, tipo 6.  Outra issue será aberta para este problema

**Comment by RedeDSBR** [comment]
Maravilha @rogerioluizsi , parabéns pela entrega!
