### ISSUE TITLE
[📊 Dados] Revisitar os dados do Indicador de Verticalização na base 2023 da PNP

### ISSUE THREAD

**Issue by RedeDSBR** [Rede-DSBR/PNP#162]
## 📝 Descrição da Solicitação

O índice de verticalização da Plataforma Nilo Peçanha (IV), busca identificar a efetividade de cada unidade acadêmica em oferecer cursos de níveis distintos em um mesmo eixo/subeixo tecnológico. Verificar o cálculo de índice de verticalização da PNP.  O IV tem como objetivo avaliar o esforço das unidades acadêmicas da Rede Federal em oferecer vagas que permitam ao estudante construir um itinerário formativo vertical, desde a Qualificação Profissional até a Pós-graduação, dentro de um mesmo Eixo Tecnológico ou Subeixo Tecnológico, conforme aponta o Inciso III do Art. 6º da Lei 11.892/2008. Este indicador busca verificar a condição de verticalização dos cursos oferecidos por uma mesma unidade acadêmica em um mesmo Eixo/Subeixo Tecnológico, considerando vagas ofertadas em 04 categorias possíveis: Curso de Qualificação Profissional (QP); Curso Técnico (CT); Curso de Graduação (CG) e Curso de Pós-Graduação (PG).

## 📅 Prazo Limite
Data de Atualização da Base 2023

**Comment by jalinegm** [comment]
Detalhamento sobre o cálculo atual (seguido desde a PNP 2017): 
https://docs.google.com/document/d/10use4z46tylmdXcSn4EPplTyMSQdBlzkaP0XdKzFaug/edit?usp=sharing

**Comment by RedeDSBR** [comment]
Fizemos um bate-papo sobre o Índice de Verticalização com Jaline e Marcel, que já tinham discutido um sobre o cálculo do índice. @jalinegm fez e refez os cálculos a partir do Referencial Metodológico. A apresentação foi gravada e foi disponibilizada no endereço.

📽 https://drive.google.com/file/d/1cv8743e0qgrbEOjKyt4gF_dyl5yQbQbe/view

**Comment by RedeDSBR** [comment]
O erro foi identificado. Trata-se do erro na fórmula descrita no quadro do Índice de Verticalização - IV constante no [Guia de Referência Metodológica](https://dadosabertos.mec.gov.br/images/pdf/grm-2020-isbn-revisado.pdf), Página 37, que está em desacordo com a metodologia empregada no cálculo do indicador.

![image](https://github.com/Rede-DSBR/PNP/assets/102130353/db5a5e6e-465e-40a2-bdb5-ac34c695de86)

A correção do erro será executada em outra tarefa.
