### ISSUE TITLE
[📊 Dados] Proposta para tratamento de ABI no SISTEC, Revalide e PNP (BI) - Cursos de Ed. Física (Resolução nº 6, de 2018)

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/PNP#201]
## 🙋‍♂️ Solicitante
Cristina Lúcia Janini Lopes, assessora técnica MEC/SETEC

## 📝 Descrição da Solicitação

A SETEC precisa ajustar o SISTEC para resolver esse problema. Além disso, estabelecer uma estratégia para adaptar a Revalide e a PNP (BI). Por isso, solicitam nossa consultoria com criação de propostas/sugestões para análise da SETEC e das outras equipes envolvidas no processo. 

Continuação da issue #192 
Documento enviado: https://docs.google.com/document/d/1UCy-pWHouUh8sTk8t3v6fgqE9yV5C1m1JSCEOLKguMc/edit

A Resolução nº 6, de 2018 Institui Diretrizes Curriculares Nacionais dos Cursos de Graduação em Educação Física e dá outras providências. A presente Resolução estabelece que o curso tenha:
I - Etapa Comum - Núcleo de estudos da formação geral, identificador da área de Educação Física, a ser desenvolvido em 1.600 (mil e seiscentas) horas referenciais, comum a ambas as formações. 
II - Etapa Específica - Formação específica a ser desenvolvida em 1.600 (mil e seiscentas) horas referenciais, na qual os graduandos terão acesso a conhecimentos específicos das opções em **bacharelado** ou **licenciatura**.

## 📊 Dados Requisitados
- Editar uma proposta sobre como o SISTEC poderia resolver o cadastro desses cursos (ciclos ABI e subciclos posteriores). Essa proposta será enviada para ajuste do SISTEC
- Propor como o Revalide poderá tratar essa situação dos ciclos, inclusive, prevendo a criação de uma nova inconsistência para validação pela rede e sugestões de como tratar os casos anteriores (correção). A Resolução é de 2017.
- Propor como pode ser ajustado o guia metodológico e eventuais fórmulas para adaptação na PNP (BI)

## 📷 Anexos
http://portal.mec.gov.br/docman/dezembro-2018-pdf/104241-rces006-18/file

![image](https://github.com/Rede-DSBR/PNP/assets/37112456/1d42e79e-9ecd-4d88-8ef1-9390cd49cc26)

Link para o documento compartilho com a solução apresentada: https://docs.google.com/document/d/1LAlyIOVK6F26OwYu47X3IzCERMS6Co8A5_MKKG-N1Uw/edit?usp=sharing

## 📅 Data de Solicitação
06/05/2024

## 📅 Prazo Limite
10/05/2024

## 🚀 Prioridade
URGENTE

**Comment by abelgamo** [comment]
Pessoal, coloquei o link do documento compartilhado com a descrição da possível solução para atendimento à Resolução. Fiquem a vontade para alterar ou fazer qualquer modificação. Coloco o link aqui também caso preferirem: https://docs.google.com/document/d/1LAlyIOVK6F26OwYu47X3IzCERMS6Co8A5_MKKG-N1Uw/edit?usp=sharing

**Comment by jalinegm** [comment]
Registro da reunião do dia 06/06/2024

https://iffarroupilhaedubr1-my.sharepoint.com/:v:/g/personal/jaline_mombach_iffarroupilha_edu_br/EUXDtjF-shREu_Wjv0SBU7UB-Dfr8cEw8nsRhnDUj8jh1A?e=SaTes3

**Comment by abelgamo** [comment]
Gravei um vídeo mostrando a tela de ciclo de matrícula porque o Leandro pediu. Deixo aqui também registrado para quem queira ver como é a tela de ciclo de matrícula no SISTEC. https://www.loom.com/share/b69840686aee4c9ab92919528fac5829?sid=0bb44564-b2bd-4be8-acdd-a110ae0a7f6f

**Comment by jalinegm** [comment]
Proposta apresentada para Cristina, dia 07/06 às 16h30min.

Slides utilizados: https://www.canva.com/design/DAGHeDKE-eY/ZZOXICwQzhtwY4GGWgsTng/view?utm_content=DAGHeDKE-eY&utm_campaign=designshare&utm_medium=link&utm_source=editor

Documento enviado por e-mail.
