### ISSUE TITLE
[🛠️ Erro] Site do Extrator Fora do Ar

### ISSUE THREAD

**Issue by RedeDSBR** [Rede-DSBR/PNP#207]
## 📝 Descreva o erro
O extrator de dados da PNP está fora do ar.

## 🖼️ Capturas de Tela

![Image](https://github.com/Rede-DSBR/PNP/assets/102130353/a92b42e7-27fa-48de-9f76-f67c8e768b62)

## 📅 Prazo Limite
28/06/2024

## 🚀 Prioridade
Alta

**Comment by damascenaluiz** [comment]
![image](https://github.com/Rede-DSBR/PNP/assets/677552/31e9200a-b6b0-4c22-b4af-e8299b9b8187)

Acessando no dia de hoje 28/06 após a issue normalmente.
