### ISSUE TITLE
[🛠️ Erro] Extrator de dados PNP desatualizado

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/PNP#208]
## 📝 Descreva o erro

No dia 08/07 foi publicada nova versão da PNP com correção nos dados.
No entanto, recebemos no formulário de demandas da rede que os dados não estão atualizados no extrator.

![image](https://github.com/Rede-DSBR/PNP/assets/37112456/cd8a9c6a-5d28-4175-8ed8-05ee82ac2267)

## 🎯 Comportamento Esperado
Os dados precisam ter os mesmos valores.

## 🚀 Prioridade
Alta

**Comment by damascenaluiz** [comment]
Atualizado
