### ISSUE TITLE
[🖼️ Conteúdo] Produção de material para data comemorativa 

### ISSUE THREAD

**Issue by Tamiresbarretoo** [Rede-DSBR/PNP#210]
# 📝🖼️ Produção de material para data comemorativa dia do Motorista 

## 📖 Descrição
Criar um card comemorativo para o dia do Motorista 

## 📌 Tipo de Conteúdo
Card 1080x1080
Card 1080 x 1920

## 🗓️ Data de Publicação Prevista
25.07.2024

## ✅ Revisores
@dudabastos1973

## 🙋 Pessoa Responsável
@Tamiresbarretoo 
@joy-araujo 

## 🚀 Data de Início
24.07.2024

## 🏁 Data de Conclusão Prevista
25.07.2024

**Comment by joy-araujo** [comment]
Dia do Motorista: **Aprovado**

- Feed:

![Feed](https://github.com/user-attachments/assets/0f44bf3c-d745-42bb-933a-f778fcd9817a)

- Stories:
![Uploading Stories.png…]()

**Comment by joy-araujo** [comment]
Dia do Motorista: **Aprovado**

- Feed:

![Feed](https://github.com/user-attachments/assets/d096300e-4424-4da6-a94a-c124d83da647)

- Stories:

![Stories](https://github.com/user-attachments/assets/64f96516-1755-4e59-8596-f21cef1bd8b9)
