### ISSUE TITLE
Seleção de servidores da Rede Federal de Educação Profissional, Científica e Tecnológica para concessão de bolsa de pesquisa

### ISSUE THREAD

**Issue by bmarbueno** [Rede-DSBR/PNP#5]
# Descrição

Chamamento Nº 02/2023 - Seleção de pesquisadores para o projeto Plataforma Nilo Peçanha: Democratização de Dados da Rede Federal da Educação Profissional, Científica e Tecnológica (Publicado em 23/09/2023. Alterado em 01/010/2023)

# Objeto

A presente tarefa tem como objeto realizar chamamento para seleção de servidores da Rede Federal de Educação Profissional, Científica e Tecnológica para concessão de bolsa de pesquisa, de acordo com a Lei nº 8.958/1994, o Decreto nº 7.423/2010 e o Contrato de Pesquisa 14/2023 celebrado entre a Universidade Federal do Oeste da Bahia (UFOB) e a Fundação de Apoio à Pesquisa e à Extensão (FAPEX).

# Pasta de Arquivos

1. [Acesse aqui a pasta de arquivos de elaboração do edital](https://drive.google.com/open?id=168bZ-OE7IOfdRQGi6gsNLmzBitIgY01V&usp=drive_fs).
1. [Acesse aqui a pasta de arquivos de execução do edital](https://drive.google.com/open?id=1FbVMmBvStrkt3piLim1aqkAVmcmKXsSS&usp=drive_fs).

# Link para Publicação do Edital
Publicação, cronograma, inscrições realizadas, resultado da seleção [Acesse aqui](https://dsbr.org/2023/09/23/chamamento022023/)

# Check-list de acompanhamento
- [x] Edital elaborado
- [x] Formulário de Inscrição desenvolvido
- [x] Infraestrutura analítica para monitoramento do processo seletivo desenvolvida
- [x] Edital publicado
- [x] Entrevistas realizadas
- [x] Seleção realizada
- [x] Resultado publicado
- [x] Bolsas de pesquisa concedidas

**Comment by bmarbueno** [comment]
- [ ] Anúncio de vagas
- [ ] Processo de seleção
- [ ] Treinamento e orientação dos bolsistas
- [ ] Supervisão das atividades dos bolsistas

**Comment by RedeDSBR** [comment]
# Pasta de Arquivos

1. [Acesse aqui a pasta de arquivos de elaboração do edital](https://drive.google.com/open?id=1MsbylBZK9Qn6kz2zZ3_FA7-Y7XVOQHq8&usp=drive_fs).
1. [Acesse aqui a pasta de arquivos de execução do edital](https://drive.google.com/open?id=1MsbylBZK9Qn6kz2zZ3_FA7-Y7XVOQHq8&usp=drive_fs).
2. 

# Link para Publicação do Edital

[Acesse aqui](https://dsbr.org/2023/09/23/chamamento022023/)

**Comment by RedeDSBR** [comment]
As bolsas do Edital de Chamamento Nº 02/2023 - Seleção de pesquisadores para o projeto Plataforma Nilo Peçanha: Democratização de Dados da Rede Federal da Educação Profissional, Científica e Tecnológica foram pagas com sucesso. Observamos que a bolsa do pesquisador @webertavaresjr não concedida pois a solicitação emissão do Ato Decisório pelo Instituto Federal de Goiás passa pela pacificação de entendimentos para o pagamento de Bolsas de Fundação de Apoio para Servidores em Afastamento para qualificação, o que é aguardado para prosseguimento do processo e abertura de nova tarefa.
