### ISSUE TITLE
Contratação de serviço audiovisual produção de artefatos de design e comunicação na III Semana Nacional da EPT

### ISSUE THREAD

**Issue by RedeDSBR** [Rede-DSBR/PNP#58]
# Descrição

contratação de Serviço de apoio a eventos para captação de imagens e artefatos visuais para composição visual de Plataforma Nilo Peçanha (PNP) para o Projeto de Pesquisa Plataforma Nilo Peçanha: Democratização de Dados.

# Objeto

O presente termo tem por objeto realizar contratação de Serviço de apoio a eventos para captação de imagens e artefatos visuais para composição visual de Plataforma Nilo Peçanha (PNP) para o Projeto de Pesquisa Plataforma Nilo Peçanha: Democratização de Dados da Rede Federal da Educação Profissional, Científica e Tecnológica (Cód. Fapex 230039).

# Check-list de acompanhamento

- [x] Elaboração do Termo de Referência
- [x] Solicitação encaminhada para a fundação de apoio
- [x] Solicitação de propostas da coleta de preços
- [x] Encaminhamento de propostas e mapa da coleta de preços
- [x] Autorização da Coordenação para aquisição
- [x] Ordem de Fornecimento
- [x] Disponibilização dos produtos
- [x] Pagamento

[O serviço estará concluído após o pagamento.]

# Pasta de Arquivos

1. [Termo de Referência](https://drive.google.com/open?id=1VC9wEv0BNapFKuA2Gevm-KCcyeMfOHA5&usp=drive_fs).
1. [Mapa de Apuração de Preços](https://drive.google.com/open?id=1b-aS-K-LMO8xmSL9nyOK8GPuf_Y4lfNN&usp=drive_fs)
1. [Proposta selecionada](https://drive.google.com/open?id=18wG_AqNop5-F-IX-XG9vE0K0eolNEoTz&usp=drive_fs)
1. [Ateste de Despesas](https://drive.google.com/open?id=1b98tD-YqIAB_h98qZXFS9nguI_YbwVIa&usp=drive_fs)
1. [Pagamentos](Inserir link)
1. [Outros documentos](Inserir link)

# Entrega dos serviços prestados

1. 📸 Pasta de arquivos de fotos e vídeos (Inserir link)

**Comment by RedeDSBR** [comment]
Inserir link de pasta de arquivo de fotos e vídeos. Responsável @dudabastos1973.

**Comment by dudabastos1973** [comment]
Link vídeos [https://drive.google.com/drive/folders/1lHGGw6uUV0r9RRnIpysiXffrFDaraH64](url)
