### ISSUE TITLE
[🖼️ Conteúdo] Premiação no I Concurso de Boas Práticas do Ministério da Educação - MEC

### ISSUE THREAD

**Issue by RedeDSBR** [Rede-DSBR/PNP#64]
# Premiação no I Concurso de Boas Práticas para incentivo à governança e à integridade no âmbito do Ministério da Educação - MEC

## Descrição

A Plataforma Nilo Peçanha sagrou-se vencedora sendo classificada em 1º Lugar do Prêmio do I Concurso de Boas Práticas para incentivo à governança e à integridade no âmbito do Ministério da Educação - MEC na categoria Aprimoramento da Transparência Ativa e Passiva e da Participação Social na Gestão Pública. A cerimônia de entrega da premiação do I Concurso de Boas Práticas do MEC - dia 28/11 às 10h no Auditório do MGI, no dia 28 de novembro de 2023, as 10h, no auditório Celso Furtado localizado no subsolo do Ministério da Gestão e Inovação de Serviços Públicos (MGI) – Bloco K da Esplanada dos Ministérios, quando da realização do I Seminário Anual de Controle Interno – SACI/MEC.

Esta tarefa tem como objetivo a criação de conteúdo sobre a premiação para divulgação nas redes sociais e encaminhamento de briefing e material para a publicação no CCET, UFOB, APUB e Fapex.

## Tipo de Conteúdo
- Post para feed, stories e reels;
- Briefing de Notícia para divulgação;
- Card comemorativo;
- Vídeo;

## Tópicos a Serem Abordados
- A Plataforma Nilo Peçanha é Desenvolvida pela UFOB em parceria com a Secretaria de Educação Profissional e Tecnológica (SeteC/MEC);
- A PNP foi 1º Lugar na Categoria Aprimoramento da Transparência Ativa e Passiva e da Participação Social na Gestão Pública;
- O desenvolvimento da PNP é liderado pela Rede DSBR, grupo de pesquisadores que desenvolve projetos premiados.
- Weber Tavares, Pesquisador Educacional da Rede DSBR, participou da criação da PNP;

## Objetivo do Conteúdo

Divulgar a PNP como uma plataforma premiada, consolidar a Rede DSBR como um grupo que desenvolve projetos premiados, reafirmar a liderança e coordenação do Prof. Poty Lucena

## 🎯 Público-Alvo
Rede da EPCT, Universidades Federais, UFOB, Fapex, APUB, Público em geral.

## 🗓️ Data de Publicação Prevista 
Segunda-feira, 27/11/2023

##  🖼️ Mídias e Arquivos de Apoio

[Post divulgado no Instagram](https://www.instagram.com/reel/Cer2t2IABSO/?utm_source=ig_web_copy_link&igshid=MzRlODBiNWFlZA==)
[Lançamento da PNP no YouTube](https://www.youtube.com/live/bZ4uf2n0BaE?si=Vs8t_gGWzws6vljI)
[Arquivo da postagem sobre o lançamento da PNP no Canva](https://www.canva.com/design/DAFDV5PoYKs/XqJKBdSZ9aODk-DLNlnukA/edit?utm_content=DAFDV5PoYKs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
[Pasta de Arquivos de Fotos do Lançamento da PNP](https://drive.google.com/drive/folders/1mWz9_qYy7Js956Mkd9Kb6bLkopq9otVz?usp=drive_link)
[Pasta de Arquivos de Vídeos do Lançamento da PNP](https://drive.google.com/drive/folders/1RnjA9KcNB0QqfH0U_nYh-dwuLJp_YZ3Q?usp=drive_link)

## Data de Início 🚀
Domingo, 26/11/2023

## Data de Conclusão Prevista 🏁
Segunda-feira, 27/11/2023

**Comment by RedeDSBR** [comment]
Os links das fotos e vídeos do lançamento da PNP foram inseridos na tarefa.

**Comment by dudabastos1973** [comment]
@RedeDSBR segue o sketch da publicação, amanhã junto o material com os vídeos (me mande o link)
Teaser (cenas vibrantes e rápidas do acontecimento PNP com vinhetas): 
Prepare-se para aplaudir. 
Plataforma Nilo Peçanha: Destaque Nacional na Governança Educacional.
Classificada em 1º lugar no Prêmio de Boas Práticas do MEC, na categoria de Transparência e Participação Social, a Plataforma Nilo Peçanha receberá, amanhã, o merecido reconhecimento nacional. Este é um marco para a SeteC/MEC e a UFOB. Sob a liderança sólida da Rede DSBR e do Prof. Poty Lucena, a PNP se destaca como uma referência em excelência na gestão pública educacional. Fique atento para testemunhar essa vitória.

**Comment by dudabastos1973** [comment]
Tarefa concluída com êxito
