### ISSUE TITLE
Adicionar testes de consistência e verificação dos CDN's

### ISSUE THREAD

**Issue by Atzingen** [Rede-DSBR/PNP#70]
Um script rodando em um cron job a cada X minutos, verificando o máximo de elementos para manter a documentação, o extrator e a página base da PNP. Um aviso no slack e e-mail será enviado quando algum problema ocorrer.

**Comment by Atzingen** [comment]
@RedeDSBR as máquinas virtuais serão todas migradas para a Azure ou ainda será usado AWS e Google Cloud ?
Tanto esses testes de consistência como a própria extração da documentação (já fiz os testes e vai dar certo puxar tudo com python via xmla) podem ser feitos de uma máquina virtual ou então de um processo serverless ( amazon lambda, google app engine ou com o github actions ).

**Comment by RedeDSBR** [comment]
Ainda não sei. Vamos fazer uma avaliação da Azure a partir do dian15/01.

**Comment by Atzingen** [comment]
Utilizando google cloud portanto fechando a issue.
